@startuml
skinparam usecase {
	BackgroundColor<< NEW >> DarkSeaGreen
	BorderColor<< NEW >> YellowGreen
}

actor App
actor Comp
actor Registry

App ..> Comp
App ..> Registry
Registry ..>Comp

usecase COMP_DESC as "
Has descriptor
---
ID
Name
Version
Package
Option descs
Events
"

usecase COMP_OPTIONS as "
Has options
"

usecase COMP_EVENT_REGISTRY as "
Has event registry
"

note as COMP_NAME_NOTE
Name is unique per app
end note

note as COMP_OPTION_DESCS_NOTE
Option descriptors declare the
component functionality
end note

note as COMP_OPTIONS_NOTE
Options provide the
component functionality
end note

COMP_OPTIONS .. COMP_OPTIONS_NOTE
COMP_DESC .. COMP_OPTION_DESCS_NOTE
COMP_OPTIONS_NOTE=.COMP_OPTION_DESCS_NOTE

usecase COMP_LOGGER as "Has logger"

Comp --> COMP_DESC
Comp --> COMP_OPTIONS
Comp --> COMP_LOGGER
Comp --> COMP_EVENT_REGISTRY
COMP_DESC .. COMP_NAME_NOTE

usecase REGISTER_COMP as "Register comp"

usecase GET_COMP_BY_ID as "
Find comp
by ID"

usecase GET_COMP_BY_NAME as "
Find comp
by name"

usecase GET_ALL_COMPS as "
Get all
registered comps"

usecase AUTO_REGISTER_EVENTS as "
Registers comp events with
the app event registry
"

Registry --> REGISTER_COMP
Registry --> GET_COMP_BY_ID
Registry --> GET_COMP_BY_NAME
Registry --> GET_ALL_COMPS
App --> AUTO_REGISTER_EVENTS
AUTO_REGISTER_EVENTS .> Registry
@enduml