@startuml
skinparam usecase {
	BackgroundColor<< NEW >> DarkSeaGreen
	BorderColor<< NEW >> YellowGreen
}
actor :App : as APP
actor :Event Registry :as EVENT_REGISTRY <<Service>>

usecase LOG_EVENT as "All log events are
statically defined"

usecase EVENT_TAGS as "Events can be tagged"

usecase PACKAGE_LOGGER as "All log events contain a
package field"

note bottom of PACKAGE_LOGGER {
The package field is the name of
the go package that logged the event.
}

usecase STD_LOG_FIELDS as "Standard log fields
are defined"

APP --> LOG_EVENT
APP --> STD_LOG_FIELDS
APP .up.> EVENT_REGISTRY

STD_LOG_FIELDS ..> PACKAGE_LOGGER
LOG_EVENT ..> EVENT_TAGS

usecase REGISTER_EVENT as "Register event"

usecase LIST_EVENTS as "
Get registered
events"

usecase FILTER_EVENTS as "Filter events"

EVENT_REGISTRY -up-> REGISTER_EVENT
EVENT_REGISTRY -up-> LIST_EVENTS
EVENT_REGISTRY -up-> FILTER_EVENTS

@enduml