/*
 * Copyright (c) 2019 OysterPack, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package fx

import (
	"github.com/oysterpack/partire-k8s/pkg/app/logging"
	"github.com/rs/zerolog"
)

// AppTag is the tag used to indicate that the events were generated by the app container.
const AppTag logging.Tag = "app"

var (
	// Start signals that the app is starting.
	Start = logging.NewEvent("start", zerolog.NoLevel, AppTag)

	// Running signals that the app is running.
	Running = logging.NewEvent("running", zerolog.NoLevel, AppTag)

	// StopSignal indicates that the stop signalled has been received
	StopSignal = logging.NewEvent("stop_signal", zerolog.NoLevel, AppTag)

	// Stop signals that the app is stopping.
	Stop = logging.NewEvent("stop", zerolog.NoLevel, AppTag)

	// Stopped signals that the app has stopped.
	Stopped = logging.NewEvent("stopped", zerolog.NoLevel, AppTag)
)
