@startuml
actor :App : as APP

usecase STD_ERRORS as "All errors are
statically defined"

usecase ERR_INSTANCE as "All error instances are
linked with a source
location via a ULID"

usecase ERR_TAGS as "Errors can be tagged"

usecase STD_TAGS as "Standard error tags
are predefined"

usecase ERR_CAUSE as "New error instances
can wrap an error cause"

usecase ERR_STACK as "Errors can be configured
to log the stack"

usecase ERR_INSTANCE_ID as "Each error instance is
assigned a unique ULID"

STD_ERRORS ..> ERR_TAGS
STD_ERRORS ..> ERR_STACK
ERR_INSTANCE ..> ERR_CAUSE
ERR_INSTANCE ..> ERR_INSTANCE_ID
ERR_TAGS ..> STD_TAGS

APP --> STD_ERRORS
APP --> ERR_INSTANCE
@enduml