@startuml

interface "Event Stream" as EventStream
interface EventStream
interface Metrics

interface "Event Writer" as EventWriter
interface "Event Query" as EventReader

interface "Metric Writer" as MetricWriter
interface "Metric Query" as MetricReader

note as EventStreamNotes
stderr
end note

EventStream .> EventStreamNotes

[App] -- EventStream
[App] -- HealthChecks
[App] -- Metrics

[Operator] .up.> HealthChecks

[AppEventLogger] .up.> EventStream
[AppEventLogger] ..> EventWriter
[AppEventLogger] ..> MetricWriter

[EventRepository] -up- EventWriter
[EventRepository] -- EventReader

[MetricRepository] -up- MetricWriter
[MetricRepository] -- MetricReader

[Dashboard] .up.> MetricReader
[Dashboard] .up.> EventReader

[AlarmManager]
[AlarmRepository]

[Job]
[JobManager]
[JobRepository]

@enduml