@startuml
actor :App : as APP

usecase APP_ID <<envconfig>> as "App has an ID"

usecase APP_NAME <<envconfig>> as "App has a name"

usecase APP_VERSION <<envconfig>> as "App has a version"

usecase APP_RELEASE_ID <<envconfig>> as "App has a release ID"

usecase APP_INSTANCE_ID as "Each running app instance
has a unique instance ID"

usecase APP_ENVCONFIG <<envconfig>> as "App env vars are
prefixed with APPX12"

usecase APP_START_TIMEOUT <<envconfig>> as "App has a start timeout"

usecase APP_STOP_TIMEOUT <<envconfig>> as "App has a stop timeout"

note as DEFAULT_TIMEOUT
Default timeout = 15s
end note

APP_START_TIMEOUT .up. DEFAULT_TIMEOUT
APP_STOP_TIMEOUT .up. DEFAULT_TIMEOUT

APP --> APP_ID
APP --> APP_NAME
APP --> APP_VERSION
APP --> APP_RELEASE_ID
APP -left-> APP_INSTANCE_ID
APP -> APP_ENVCONFIG
APP -up-> APP_START_TIMEOUT
APP -up-> APP_STOP_TIMEOUT

@enduml